# Path to intersection TSV files produced by the callset-comparison pipeline and the VCF files to be filtered in order to obtain the VCF with the rare disease patients exclusive variants.
intersections:
  name1:
    table: "/path/to/intersect1.tsv"
    vcf: "/path/to/vcf1.vcf"
  name2:
    table: "/path/to/intersect2.tsv"
    vcf: "/path/to/vcf2.vcf"

# Path to reference genome must be provided for the extraction of the alleles not intersecting with SAGA
reference: "/path/to/ref"

# Path to the augmented graph, to realign the extracted alleles against
aug_graph: "/path/to/graph"

# List with information on the callsets used for the intersection: First element corresponds to the number of patient's callsets, second element is the total number of callsets included
callsets: [2, 4]
# The list assumes an order of:
# callsets[0] of patient's callsets, followed by SAGA's callset in position callsets[0]+1, plus as many callsets[1]-callsets[0]+1 additional callsets present in the intersection
# VCFs generated by the pipeline will assume the representation of the VCF given first in the intersection pipeline's order